#!/usr/bin/env bash
# Writes a bash script that displays listening ports.
# Displays only listening sockets.
# Displays the PID and the name of the program to which each socket belongs.

sudo netstat --listening --program
