#!/usr/bin/env bash
# The function of this script is to write its own PID to file and respond to signals.

file=/var/run/myscript.pid

cleanup() {
    echo "Y U no love me?!"
    rm -f "$file"
    exit
}

trap cleanup SIGINT
trap cleanup SIGQUIT
trap cleanup SIGTERM

echo $$ > "$file"

while true; do
    echo "To infinity and beyond"
    sleep 2
done
