#!/usr/bin/env bash
# The function of this script is to manage a daemon process.

PIDFILE=/var/run/my_process.pid

if [ "$1" = "start" ]; then
    ./manage_my_process &
    echo "$!" > "$PIDFILE"
    echo "manage_my_process started"
elif [ "$1" = "stop" ]; then
    if [ -f "$PIDFILE" ]; then
        pid=$(cat "$PIDFILE")
        kill -TERM "$pid"
        rm "$PIDFILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
elif [ "$1" = "restart" ]; then
    if [ -f "$PIDFILE" ]; then
        pid=$(cat "$PIDFILE")
        kill -TERM "$pid"
        rm "$PIDFILE"
        ./manage_my_process &
        echo "$!" > "$PIDFILE"
        echo "manage_my_process restarted"
    else
        ./manage_my_process &
        echo "$!" > "$PIDFILE"
        echo "manage_my_process started"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
