#!/usr/bin/env bash
# A bash script that displays listening ports.
# Shows only listening sockets.
# Shows the PID and the name of the program to which each socket belongs.

sudo netstat --listening --program
